### ISSUE TITLE
Unit card images needs updating

### ISSUE THREAD

**Issue by mobergio** [achapin/wastelandworkshop#19]
As I was building a raider list I noticed that with the new armor rules, per the nuka cola expansion, the effect on the **Light Armored** ability (_Movements are one color shorter if any armor or clothing is used_) on the **Psycho** unit now made the unit more or less unplayable. But then I noticed that the unit had gotten an errata, and now it reads 
> If this model has any armor value higher than 2, movements are one color shorter. Immunity (X) counts as armor 0 for the purposes of this rule.

Since you have a checkbox for using the armor values on the card, perhaps you could use that toggle to switch between the two images of the cards that have erratas?

**Comment by mobergio** [comment]
I created a pr (see #20). Feel free to do with that what you will :)

**Comment by achapin** [comment]
Closed with #20
