### ISSUE TITLE
Pointcost on none unique units

### ISSUE THREAD

**Issue by DH2202** [achapin/wastelandworkshop#3]
First great work. But could you please fix the bug with the wrong point Costa for Perks, etc on none unique units?

**Comment by achapin** [comment]
I'm not sure what you mean. Non-unique units can have perks, and they cost the same as unique units.

**Comment by DH2202** [comment]
What i mean is, when i use e.g. two minuteman and make the first one a hero or give him a perk, the Cost will be added also to the second one. So i can't build two different minutemans

**Comment by achapin** [comment]
Ah, I see now. Yeah, that'll be fixed soon.

**Comment by achapin** [comment]
Fixed this today. If you still see it, make sure to hard-reload the page.
